/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wlmfcqkzlacdncfxajsf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbWZjcWt6bGFjZG5jZnhhanNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMzEyNjAsImV4cCI6MjA3OTYwNzI2MH0.S8Ut0O8BGje2vA-gaTNzWy-dQLe-_X5LeEiuwcZvZxA"