// 完整的A股本地数据库
export const STOCK_DATABASE = [
  {"code": "600519", "name": "贵州茅台", "market": "SH", "industry": "白酒"},
  {"code": "600036", "name": "招商银行", "market": "SH", "industry": "银行"},
  {"code": "601318", "name": "中国平安", "market": "SH", "industry": "保险"},
  {"code": "000858", "name": "五粮液", "market": "SZ", "industry": "白酒"},
  {"code": "002594", "name": "比亚迪", "market": "SZ", "industry": "新能源车"},
  {"code": "300750", "name": "宁德时代", "market": "SZ", "industry": "新能源"},
  {"code": "000001", "name": "平安银行", "market": "SZ", "industry": "银行"},
  {"code": "000002", "name": "万科A", "market": "SZ", "industry": "房地产"},
  {"code": "000063", "name": "中兴通讯", "market": "SZ", "industry": "通信设备"},
  {"code": "000100", "name": "TCL科技", "market": "SZ", "industry": "家电"},
  {"code": "000333", "name": "美的集团", "market": "SZ", "industry": "家电"},
  {"code": "000338", "name": "潍柴动力", "market": "SZ", "industry": "机械"},
  {"code": "000538", "name": "云南白药", "market": "SZ", "industry": "医药"},
  {"code": "000568", "name": "泸州老窖", "market": "SZ", "industry": "白酒"},
  {"code": "000596", "name": "古井贡酒", "market": "SZ", "industry": "白酒"},
  {"code": "000651", "name": "格力电器", "market": "SZ", "industry": "家电"},
  {"code": "000725", "name": "京东方A", "market": "SZ", "industry": "面板"},
  {"code": "000776", "name": "广发证券", "market": "SZ", "industry": "证券"},
  {"code": "000799", "name": "酒鬼酒", "market": "SZ", "industry": "白酒"},
  {"code": "000876", "name": "新希望", "market": "SZ", "industry": "农业"},
  {"code": "000895", "name": "双汇发展", "market": "SZ", "industry": "食品"},
  {"code": "000977", "name": "浪潮信息", "market": "SZ", "industry": "计算机"},
  {"code": "002008", "name": "大族激光", "market": "SZ", "industry": "机械"},
  {"code": "002027", "name": "分众传媒", "market": "SZ", "industry": "传媒"},
  {"code": "002049", "name": "紫光国微", "market": "SZ", "industry": "半导体"},
  {"code": "002129", "name": "中环股份", "market": "SZ", "industry": "半导体"},
  {"code": "002142", "name": "宁波银行", "market": "SZ", "industry": "银行"},
  {"code": "002230", "name": "科大讯飞", "market": "SZ", "industry": "人工智能"},
  {"code": "002304", "name": "洋河股份", "market": "SZ", "industry": "白酒"},
  {"code": "002352", "name": "顺丰控股", "market": "SZ", "industry": "物流"},
  {"code": "002371", "name": "北方华创", "market": "SZ", "industry": "半导体设备"},
  {"code": "002415", "name": "海康威视", "market": "SZ", "industry": "安防"},
  {"code": "002460", "name": "赣锋锂业", "market": "SZ", "industry": "锂电池"},
  {"code": "002466", "name": "天齐锂业", "market": "SZ", "industry": "锂电池"},
  {"code": "002475", "name": "立讯精密", "market": "SZ", "industry": "消费电子"},
  {"code": "002607", "name": "中公教育", "market": "SZ", "industry": "教育"},
  {"code": "002624", "name": "完美世界", "market": "SZ", "industry": "游戏"},
  {"code": "002714", "name": "牧原股份", "market": "SZ", "industry": "农业"},
  {"code": "002812", "name": "恩捷股份", "market": "SZ", "industry": "锂电池"},
  {"code": "002821", "name": "凯莱英", "market": "SZ", "industry": "医药"},
  {"code": "002841", "name": "视源股份", "market": "SZ", "industry": "电子"},
  {"code": "002938", "name": "鹏鼎控股", "market": "SZ", "industry": "PCB"},
  {"code": "300003", "name": "乐普医疗", "market": "SZ", "industry": "医疗器械"},
  {"code": "300014", "name": "亿纬锂能", "market": "SZ", "industry": "锂电池"},
  {"code": "300059", "name": "东方财富", "market": "SZ", "industry": "互联网金融"},
  {"code": "300124", "name": "汇川技术", "market": "SZ", "industry": "工控"},
  {"code": "300142", "name": "沃森生物", "market": "SZ", "industry": "疫苗"},
  {"code": "300274", "name": "阳光电源", "market": "SZ", "industry": "光伏"},
  {"code": "300347", "name": "泰格医药", "market": "SZ", "industry": "CRO"},
  {"code": "300408", "name": "三环集团", "market": "SZ", "industry": "电子"},
  {"code": "300413", "name": "芒果超媒", "market": "SZ", "industry": "传媒"},
  {"code": "300502", "name": "新易盛", "market": "SZ", "industry": "光模块"},
  {"code": "300529", "name": "健帆生物", "market": "SZ", "industry": "医疗器械"},
  {"code": "300595", "name": "欧普康视", "market": "SZ", "industry": "医疗器械"},
  {"code": "300601", "name": "康泰生物", "market": "SZ", "industry": "疫苗"},
  {"code": "300628", "name": "亿联网络", "market": "SZ", "industry": "通信"},
  {"code": "300760", "name": "迈瑞医疗", "market": "SZ", "industry": "医疗器械"},
  {"code": "300782", "name": "卓胜微", "market": "SZ", "industry": "半导体"},
  {"code": "600000", "name": "浦发银行", "market": "SH", "industry": "银行"},
  {"code": "600009", "name": "上海机场", "market": "SH", "industry": "机场"},
  {"code": "600015", "name": "华夏银行", "market": "SH", "industry": "银行"},
  {"code": "600016", "name": "民生银行", "market": "SH", "industry": "银行"},
  {"code": "600019", "name": "宝钢股份", "market": "SH", "industry": "钢铁"},
  {"code": "600028", "name": "中国石化", "market": "SH", "industry": "石油化工"},
  {"code": "600029", "name": "南方航空", "market": "SH", "industry": "航空"},
  {"code": "600030", "name": "中信证券", "market": "SH", "industry": "证券"},
  {"code": "600031", "name": "三一重工", "market": "SH", "industry": "工程机械"},
  {"code": "600048", "name": "保利发展", "market": "SH", "industry": "房地产"},
  {"code": "600050", "name": "中国联通", "market": "SH", "industry": "电信运营"},
  {"code": "600104", "name": "上汽集团", "market": "SH", "industry": "汽车"},
  {"code": "600111", "name": "北方稀土", "market": "SH", "industry": "稀土"},
  {"code": "600115", "name": "中国东航", "market": "SH", "industry": "航空"},
  {"code": "600132", "name": "重庆啤酒", "market": "SH", "industry": "啤酒"},
  {"code": "600176", "name": "中国巨石", "market": "SH", "industry": "建材"},
  {"code": "600196", "name": "复星医药", "market": "SH", "industry": "医药"},
  {"code": "600197", "name": "伊力特", "market": "SH", "industry": "白酒"},
  {"code": "600219", "name": "南山铝业", "market": "SH", "industry": "铝"},
  {"code": "600276", "name": "恒瑞医药", "market": "SH", "industry": "医药"},
  {"code": "600309", "name": "万华化学", "market": "SH", "industry": "化工"},
  {"code": "600346", "name": "恒力石化", "market": "SH", "industry": "化工"},
  {"code": "600362", "name": "江西铜业", "market": "SH", "industry": "有色金属"},
  {"code": "600383", "name": "金地集团", "market": "SH", "industry": "房地产"},
  {"code": "600426", "name": "华鲁恒升", "market": "SH", "industry": "化工"},
  {"code": "600436", "name": "片仔癀", "market": "SH", "industry": "中药"},
  {"code": "600438", "name": "通威股份", "market": "SH", "industry": "光伏"},
  {"code": "600498", "name": "烽火通信", "market": "SH", "industry": "通信设备"},
  {"code": "600547", "name": "山东黄金", "market": "SH", "industry": "黄金"},
  {"code": "600559", "name": "老白干酒", "market": "SH", "industry": "白酒"},
  {"code": "600585", "name": "海螺水泥", "market": "SH", "industry": "水泥"},
  {"code": "600588", "name": "用友网络", "market": "SH", "industry": "软件"},
  {"code": "600600", "name": "青岛啤酒", "market": "SH", "industry": "啤酒"},
  {"code": "600606", "name": "绿地控股", "market": "SH", "industry": "房地产"},
  {"code": "600660", "name": "福耀玻璃", "market": "SH", "industry": "汽车零部件"},
  {"code": "600690", "name": "海尔智家", "market": "SH", "industry": "家电"},
  {"code": "600702", "name": "舍得酒业", "market": "SH", "industry": "白酒"},
  {"code": "600745", "name": "闻泰科技", "market": "SH", "industry": "消费电子"},
  {"code": "600779", "name": "水井坊", "market": "SH", "industry": "白酒"},
  {"code": "600809", "name": "山西汾酒", "market": "SH", "industry": "白酒"},
  {"code": "600837", "name": "海通证券", "market": "SH", "industry": "证券"},
  {"code": "600872", "name": "中炬高新", "market": "SH", "industry": "食品"},
  {"code": "600887", "name": "伊利股份", "market": "SH", "industry": "乳制品"},
  {"code": "600900", "name": "长江电力", "market": "SH", "industry": "电力"},
  {"code": "600926", "name": "杭州银行", "market": "SH", "industry": "银行"},
  {"code": "600941", "name": "中国移动", "market": "SH", "industry": "电信运营"},
  {"code": "600958", "name": "东方证券", "market": "SH", "industry": "证券"},
  {"code": "600999", "name": "招商证券", "market": "SH", "industry": "证券"},
  {"code": "601009", "name": "南京银行", "market": "SH", "industry": "银行"},
  {"code": "601012", "name": "隆基绿能", "market": "SH", "industry": "光伏"},
  {"code": "601111", "name": "中国国航", "market": "SH", "industry": "航空"},
  {"code": "601166", "name": "兴业银行", "market": "SH", "industry": "银行"},
  {"code": "601169", "name": "北京银行", "market": "SH", "industry": "银行"},
  {"code": "601211", "name": "国泰君安", "market": "SH", "industry": "证券"},
  {"code": "601229", "name": "上海银行", "market": "SH", "industry": "银行"},
  {"code": "601288", "name": "农业银行", "market": "SH", "industry": "银行"},
  {"code": "601319", "name": "中国人保", "market": "SH", "industry": "保险"},
  {"code": "601328", "name": "交通银行", "market": "SH", "industry": "银行"},
  {"code": "601336", "name": "新华保险", "market": "SH", "industry": "保险"},
  {"code": "601398", "name": "工商银行", "market": "SH", "industry": "银行"},
  {"code": "601601", "name": "中国太保", "market": "SH", "industry": "保险"},
  {"code": "601628", "name": "中国人寿", "market": "SH", "industry": "保险"},
  {"code": "601668", "name": "中国建筑", "market": "SH", "industry": "建筑"},
  {"code": "601688", "name": "华泰证券", "market": "SH", "industry": "证券"},
  {"code": "601766", "name": "中国中车", "market": "SH", "industry": "轨交设备"},
  {"code": "601818", "name": "光大银行", "market": "SH", "industry": "银行"},
  {"code": "601857", "name": "中国石油", "market": "SH", "industry": "石油化工"},
  {"code": "601888", "name": "中国中免", "market": "SH", "industry": "免税"},
  {"code": "601901", "name": "方正证券", "market": "SH", "industry": "证券"},
  {"code": "601916", "name": "浙商银行", "market": "SH", "industry": "银行"},
  {"code": "601939", "name": "建设银行", "market": "SH", "industry": "银行"},
  {"code": "601988", "name": "中国银行", "market": "SH", "industry": "银行"},
  {"code": "601990", "name": "南京证券", "market": "SH", "industry": "证券"},
  {"code": "601997", "name": "贵阳银行", "market": "SH", "industry": "银行"},
  {"code": "603195", "name": "公牛集团", "market": "SH", "industry": "电器"},
  {"code": "603198", "name": "迎驾贡酒", "market": "SH", "industry": "白酒"},
  {"code": "603259", "name": "药明康德", "market": "SH", "industry": "CRO"},
  {"code": "603288", "name": "海天味业", "market": "SH", "industry": "调味品"},
  {"code": "603369", "name": "今世缘", "market": "SH", "industry": "白酒"},
  {"code": "603589", "name": "口子窖", "market": "SH", "industry": "白酒"},
  {"code": "603899", "name": "晨光文具", "market": "SH", "industry": "文具"},
  {"code": "603986", "name": "兆易创新", "market": "SH", "industry": "半导体"},
  {"code": "688005", "name": "容百科技", "market": "SH", "industry": "锂电材料"},
  {"code": "688008", "name": "澜起科技", "market": "SH", "industry": "半导体"},
  {"code": "688012", "name": "中微公司", "market": "SH", "industry": "半导体设备"},
  {"code": "688018", "name": "乐鑫科技", "market": "SH", "industry": "半导体"},
  {"code": "688036", "name": "传音控股", "market": "SH", "industry": "消费电子"},
  {"code": "688099", "name": "晶晨股份", "market": "SH", "industry": "半导体"},
  {"code": "688111", "name": "金山办公", "market": "SH", "industry": "软件"},
  {"code": "688126", "name": "沪硅产业", "market": "SH", "industry": "半导体材料"},
  {"code": "688169", "name": "石头科技", "market": "SH", "industry": "智能家居"},
  {"code": "688223", "name": "晶科能源", "market": "SH", "industry": "光伏"},
  {"code": "688256", "name": "寒武纪", "market": "SH", "industry": "AI芯片"},
  {"code": "688303", "name": "大全能源", "market": "SH", "industry": "光伏"},
  {"code": "688396", "name": "华润微", "market": "SH", "industry": "半导体"},
  {"code": "688561", "name": "奇安信", "market": "SH", "industry": "网络安全"},
  {"code": "688981", "name": "中芯国际", "market": "SH", "industry": "半导体"},
  {"code": "000166", "name": "申万宏源", "market": "SZ", "industry": "证券"},
  {"code": "000929", "name": "兰州黄河", "market": "SZ", "industry": "啤酒"},
  {"code": "002839", "name": "张家港行", "market": "SZ", "industry": "银行"}
];

// 生成随机股价
function generateRandomPrice(industry: string): number {
  const priceRanges: Record<string, [number, number]> = {
    '白酒': [100, 2000],
    '银行': [3, 50],
    '保险': [20, 80],
    '证券': [10, 40],
    '新能源车': [150, 300],
    '新能源': [50, 200],
    '半导体': [30, 200],
    '医药': [30, 150],
    '家电': [20, 100],
    '默认': [5, 100]
  };
  
  const range = priceRanges[industry] || priceRanges['默认'];
  return Math.random() * (range[1] - range[0]) + range[0];
}

// 搜索股票（本地）
export function searchStocksLocal(query: string) {
  if (!query.trim()) return [];
  
  const queryLower = query.toLowerCase();
  const results = STOCK_DATABASE.filter(stock =>
    stock.name.includes(query) ||
    stock.code.includes(query) ||
    stock.industry.includes(query)
  ).slice(0, 50);
  
  // 添加模拟价格数据
  return results.map(stock => {
    const basePrice = generateRandomPrice(stock.industry);
    const change = (Math.random() - 0.5) * basePrice * 0.1;
    const changePercent = (change / basePrice) * 100;
    
    return {
      symbol: `${stock.code}.${stock.market}`,
      name: stock.name,
      price: parseFloat(basePrice.toFixed(2)),
      change: parseFloat(change.toFixed(2)),
      changePercent: parseFloat(changePercent.toFixed(2))
    };
  });
}

console.log(`📊 本地股票数据库已加载: ${STOCK_DATABASE.length} 只股票`);
